### ISSUE TITLE
Crash upon trying to open a file

### ISSUE THREAD

**Issue by roonieone** [nothingmagical/whiskey-issues#96] opened 2015-06-06 06:15 UTC
**Steps to reproduce:**

- Close all open windows in Whiskey

- Quit Whiskey

- Re-open Whiskey

- Whiskey opens a blank document

- Try to open another document (using the keyboard shortcut, +O)

- Whiskey crashes

(I have a crash report that I can send, but GitHub doesn't seem to want to let me upload it)

**Comment by soffes** [comment] 2015-06-06 06:16
Thanks. Don't worry about uploading. I have another one.

On Fri, Jun 5, 2015 at 11:15 PM Mark Malstrom <notifications@github.com>
wrote:

> *Steps to reproduce:*
>
>    -
>
>    Close all open windows in Whiskey
>    -
>
>    Quit Whiskey
>    -
>
>    Re-open Whiskey
>    -
>
>    Whiskey opens a blank document
>    -
>
>    Try to open another document (using the keyboard shortcut, +O)
>    -
>
>    Whiskey crashes
>
> (I have a crash report that I can send, but GitHub doesn't seem to want to
> let me upload it)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nothingmagical/whiskey-issues/issues/96>.
>
-- 
Sam

**Comment by soffes** [comment] 2015-08-10 18:35
Duplicate of #91

**Closed by soffes** 2015-08-10 18:35 UTC
Labels: bug, crash
