### ISSUE TITLE
Can't type in textfield after launching

### ISSUE THREAD

**Issue by tspangler** [nothingmagical/whiskey-issues#81] opened 2015-02-07 19:56 UTC
Whiskey opens to a new document, but I can’t type anything until I toggle the preview pane on. And then, the preview pane doesn’t actually appear until I toggle it again.

The attached screencast should show the behavior, as well the console error I receive when quitting.

https://www.dropbox.com/s/9txnashw1ovy4z9/WhiskeyBugReport.m4v?dl=0

**Comment by soffes** [comment] 2015-02-07 20:09
Ya known issues with max widths for preview and outline. Thanks for reporting!

**Comment by soffes** [comment] 2015-08-12 23:18
Duplicate of #99

**Closed by soffes** 2015-08-12 23:18 UTC
