### ISSUE TITLE
Proper (cosmetic) parsing of YAML front matter

### ISSUE THREAD

**Issue by masnick** [nothingmagical/whiskey-issues#116] opened 2015-08-13 22:44 UTC
[YAML front matter](http://jekyllrb.com/docs/frontmatter/) is part of the popular [Jekyll](http://jekyllrb.com) static site generator.

The Markdown for a Jekyll blog post might look like:

```markdown
---
layout: post
title: Blogging Like a Hacker
---

Body of post goes here.
```

Whiskey 0.3.8 currently parses the lower `---` as an indicator of a heading:

![screen shot 2015-08-13 at 4 44 03 pm](https://cloud.githubusercontent.com/assets/110426/9263471/8556df50-41da-11e5-9984-ac7ef138849f.png)

**Comment by soffes** [comment] 2015-08-13 23:49
Duplicate of #11

**Closed by soffes** 2015-08-13 23:49 UTC
