### ISSUE TITLE
code blocks shown twice in preview

### ISSUE THREAD

**Issue by elliotthilaire** [nothingmagical/whiskey-issues#86] opened 2015-03-05 05:25 UTC
Code blocks using 4 spaces or a tab are shown twice in the preview pane.

The problem doesn't occur when using backtick syntax.

![screen shot 2015-03-05 at 3 21 32 pm](https://cloud.githubusercontent.com/assets/3443017/6499677/68b94396-c34b-11e4-837a-f53e5c0962bd.png)

**Comment by soffes** [comment] 2015-03-05 19:04
Duplicate of #55

**Closed by soffes** 2015-03-05 19:04 UTC
